version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - neo4j
    networks: 
      - net
  
  neo4j:
    container_name: neo4j
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NE04J_dbms.security.procedures.unrestricted=algo.\\\*
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    networks: 
      - net

networks:
  net:
    driver: bridge

volumes:
  data:
  logs:
  conf:
  neomodal:
  projects: